baseURL = "https://marcostrindade.netlify.app/"
title = "Marcos"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
title = "Marcos"
description = "Meu Blog"
keywords = ["Blog", "Portfolio", "DevOps"]
author = "Marcos Trindade"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[params.profileMode]
enabled = true
title = "Marcos Trindade"
subtitle = "DevOps Engineer"
imageUrl = "marcos.png"
imageTitle = "my image"

[[params.socialIcons]]
name = "github"
url = "https://github.com/MarcosTrindadezz"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/marcosgab"

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/Portfólio/"
weight = 10

[[menu.main]]
identifier = "sobre"
name = "Sobre Mim"
url = "/posts/sobre/"
weight = 30

[[menu.main]]
identifier = "curriculo"
name = "Currículo"
url = "https://drive.google.com/file/d/1hHZ4A5n1myURiLE1C9FiapLHq6d111tB/view?usp=sharing"
weight = 40


[markup.goldmark.renderer]
unsafe = true
