baseURL = "https://brendotrindade.netlify.app/"
title = "Brendo Blog"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
title = "Brendo Blog"
description = "Blog pessoal de Brendo Trindade"
keywords = ["Blog", "Portfolio", "DevOps"]
author = "Brendo Trindade"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[params.profileMode]
enabled = true
title = "Brendo Trindade"
subtitle = "DevOps Engineer"
imageUrl = "brendo.png"
imageTitle = "my image"

[[params.socialIcons]]
name = "github"
url = "https://github.com/MarcosTrindadezz"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/brendo-trindade-a71596251/"
