baseURL = "https://marcostrindade.netlify.app/"
title = "Marcos Trindade"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
title = "Marcos Trindade"
description = "Blog pessoal e portfólio de DevOps"
keywords = ["DevOps", "Cloud", "Infraestrutura", "Tecnologia"]
author = "Marcos Trindade"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[params.profileMode]
enabled = true
title = "Marcos Trindade"
subtitle = "DevOps Engineer"
imageUrl = "brendo.png"
imageTitle = "my image"

[[params.socialIcons]]
name = "github"
url = "https://github.com/MarcosTrindadezz"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/marcos-trindade"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "portfolio"
name = "Portfólio"
url = "/Portfólio/"
weight = 30

[[menu.main]]
identifier = "sobre"
name = "Sobre"
url = "/posts/sobre/"
weight = 40

[markup.goldmark.renderer]
unsafe = true
